### ISSUE TITLE
balance_cooler allows store_name even when store=False

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooler#202]
Should this raise an error?
https://github.com/mirnylab/cooler/blob/c9c718fdebccbda41ad10c47f700853f79ee3cd3/cooler/balance.py#L271

**Comment by nvictus** [comment]
I'm okay with this. It provides an explicit default. The alternative would be to have a hybrid store argument that takes a bool or a string. `store=True` would use an implicit default name of "weight" and `store={name}` would use the provided name.
