### ISSUE TITLE
ftp can‘t connect

### ISSUE THREAD

**Issue by esroom** [open2c/cooler#228]
It seems that the FTP site [ftp://cooler.csail.mit.edu/coolers/](url) is broken.

**Comment by nvictus** [comment]
Thanks for reporting the outage. The server is back up again.

**Comment by esroom** [comment]
Thanks for your reply. But I still cannot connect. Has the site changed?

**Comment by nvictus** [comment]
Oh.. I think there are new firewalls in place blocking access from outside MIT. I'll see what I can do.

**Comment by esroom** [comment]
There may be some problems with my browser...I change to another one and it works. Thanks a lot!
