### ISSUE TITLE
Is the matrix obtained by the cooler zoomify --balance  --balance-args “--tol 0.05" still need normalized by run cooler balance?

### ISSUE THREAD

**Issue by rachelzhu123** [open2c/cooler#231]
hi 
i got .mcool file by running the follow command line
cooler zoomify --nproc 8 --out .mcool --resolution 40000,25000 --balance  --balance-args “--tol 0.05" my.cool
I've looked at --balance parameter in the help documentation(https://cooler.readthedocs.io/en/latest/cli.html#cooler-balance), but I still don't quite understand it. Is the matrix obtained by the cooler zoomify --balance  --balance-args “--tol 0.05" still need normalized by run cooler balance?
Looking forward to your answers.
Thanks.

**Comment by Phlya** [comment]
Nope, it'll be balanced already, since you included the `--balance` argument.
Also, that's quite a high tolerance you specified, just in case you don't know.

**Comment by rachelzhu123** [comment]
wow, thaks a lot.
