### ISSUE TITLE
ConvergenceWarning: Iteration limit reached without convergence

### ISSUE THREAD

**Issue by Max-Highsmith** [open2c/cooler#235]
Hello,
I am trying to apply ICE normalizaiton to a cooler file which I derived from an aiden lab .hic file.  When trying to balance my matrix I receive an iteration limit warning. 
```
import cooler
my_cooler = cooler.Cooler("Data/Cool_files/D0_r1.mcool::/resolutions/1000000")
cooler.balance_cooler(my_cooler)
```
The Error
> /home/heracles/miniconda3/envs/melanoma_fresh/lib/python3.6/site-packages/cooler/balance.py:110: ConvergenceWarning: Iteration limit reached without convergence.
>   ConvergenceWarning)
> (melanoma_fresh) heracles
> 

 I know D0_r1.hic file is valid as it is usable by other downstream tools such as juice box.  I convert from .hic to cooler using hictocool package (https://github.com/4dn-dcic/hic2cool).  I have also tried constraining the balancing to intra-contacts  (cis_only=True), and have tried extending the iteration limit setting (max_iters=1000) but to no avail.  A matrix is returned, however, I am assuming I can not use this as there is a convergence error.  How can I obtain balanced matrices/ could you provide any insight, biological or technical, as to why this is not working?

**Comment by nvictus** [comment]
Can you try the command line `cooler balance Data/Cool_files/D0_r1.mcool::/resolutions/1000000`?
It uses sensible defaults, while the `balance_cooler` function currently has all filters off by default. I'll make an issue to change this.

The most important filters are to ignore junk ligations on the first 2 diagonals (or more at very high resolution): `ignore_diags=2`, and to remove bins with extremely low coverage: one or more of `min_count`, `min_nnz`, `mad_max`.

Alternatively, turn on logging and watch how the variance of the marginals evolves with and without filters:

```python
import logging
logger = logging.getLogger('cooler.balance')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())                                                          

cooler.balance_cooler(my_cooler)

cooler.balance_cooler(my_cooler, ignore_diags=2, mad_max=5)
```

**Comment by Max-Highsmith** [comment]
Thank you for the response. I have added the ignore_diags and mad_max terms suggested.  There is still an Iteration limit reached for chromosome Y, however, everything appears to be working for the autosomal chromosomes.
