### ISSUE TITLE
capture Hi-C

### ISSUE THREAD

**Issue by nservant** [open2c/cooler#242]
Hi @nvictus 

I was wondering if there is any function to restrict a cool object to a smaller sub-matrix.
For instance, if I do have capture Hi-C data, and would like to build a cooler object restricted to the 3Mb capture region ?
I can of course filter the data before running `cload` I guess.
Thanks
Nicolas

**Comment by nvictus** [comment]
Yes, you would have to filter as you suggested. You could also make a restricted bin table, but it would still contain one whole chromosome, and I wouldn't recommend doing that.

Alternatively, you could also just load all the data and mask out the rest of the genome for balancing by using the `--blacklist` parameter. The benefit is you'll be able to see how "enriched" the unenriched parts of the library are when looking at raw counts.

**Comment by nservant** [comment]
Thanks @nvictus.
