### ISSUE TITLE
converting a chromosome pair contact matrix to .cool to visualize in higlass

### ISSUE THREAD

**Issue by tarak77** [open2c/cooler#243]
Hi,
I have a piled-up (from single-cell) contact matrix for a chromosome pair, say chr 3 and chr7. This is in the form of numpy 2D array. Is there a way to use ArrayLoader to convert it into a .cool file to visualize in higlass? Or will I need a genomewide 2D array?

Any help will be much appreciated!
Thanks

**Comment by nvictus** [comment]
No, it expects a full genome matrix, but here's a recipe that should work for you. Assuming you place a numpy array for each chromosome-pair map in a dictionary called `contact_maps`:

```python
binsize = 100000   # or whatever the resolution is
chromsizes = cooler.fetch_chromsizes('hg38')  # or whatever your assembly is
bins = cooler.binnify(chromsizes, binsize)
chrom_col = bins['chrom'].values
offsets = dict(zip(chromsizes.index, np.r_[0, np.where(chrom_col[:-1] != chrom_col[1:])[0]]))

data = []
for chrom1, chrom2 in [('chr3', 'chr3'), ('chr3', 'chr7'), ('chr7', 'chr7')]:
    A = contact_maps[chrom1, chrom2]
    if chrom1 == chrom2:
        A = np.triu(A)
    i, j = np.where(A)
    v = A[i, j]
    i += offsets[chrom1]
    j += offsets[chrom2]
    data.append(pd.DataFrame({'bin1_id': i, 'bin2_id': j, 'count': v}))
data = pd.concat(data)

cooler.create_cooler(f'out.{binsize}.cool', bins, data)

```

**Comment by nvictus** [comment]
Oh, if you meant just the interchromosomal region for (`chr3`, `chr7`), then you can ignore the for loop and dictionary.

**Comment by tarak77** [comment]
Thank you Nezar for the quick response!
Yes, I just want to visualize the interchromosomal region for (chr3, chr7). 
Also, would I have to change the command to visualize in higlass?
Currently, I am trying to use:
`docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename /tmp/out.100000.cool --filetype cooler --datatype matrix`

It's still loading on the server

Attached is the .cool file I got.
[out.100000.cool.zip](https://github.com/open2c/cooler/files/6018893/out.100000.cool.zip)

**Comment by nvictus** [comment]
Are you sure you loaded the data correctly? It seems to include 0 values and only has 90 nonzero values. Using `np.where` is key.

Also, apologies, there was an off-by-one in the `offsets` that is fixed in the snippet below:

```python
binsize = 100000
chromsizes = cooler.fetch_chromsizes('mm10')
bins = cooler.binnify(chromsizes, binsize)
chrom_col = bins['chrom'].values
offsets = dict(zip(chromsizes.index, np.r_[0, np.where(chrom_col[:-1] != chrom_col[1:])[0] + 1]))

chrom1 = 'chr3'
chrom2 = 'chr7'
i, j = np.where(A)  # get the nonzero elements
data = pd.DataFrame({'bin1_id': i + offsets[chrom1], 'bin2_id': j + offsets[chrom2], 'count': A[i, j]}))
cooler.create_cooler(f'out.{binsize}.cool', bins, data)
```

The command you used should work. You might find [higlass-manage](https://github.com/higlass/higlass-manage) useful.

**Comment by tarak77** [comment]
Thank you for checking that. I think I fixed the part of generating the .cool file.
I have installed cooler using pip3. 
I am trying to run cooler using command line:

```
Taraks-MacBook-Pro:~ tarakshisode$ which cooler
/Users/tarakshisode/anaconda3/bin/cooler
Taraks-MacBook-Pro:~ tarakshisode$ 
Taraks-MacBook-Pro:~ tarakshisode$ cooler
-bash: /usr/local/bin/cooler: No such file or directory
```

It might be trivial but I think I am missing something?

**Comment by tarak77** [comment]
Hey Nezar,
I got the .mcool file working on higlass using the docker instance. 
If I want to overlay the gene track on this interchromosomal contact map, can I use the default gene tracks present in higlass?

Thanks!

Attached is the .mcool file
[chr3m_7m_8cse.100000.mcool.zip](https://github.com/open2c/cooler/files/6023742/chr3m_7m_8cse.100000.mcool.zip)

**Comment by nvictus** [comment]
The default gene track should work provided it's the same genome assembly. Generally, for HiGlass-specific questions, feel free to ask on the HiGlass [Slack](https://rb.gy/q9do1b).
