### ISSUE TITLE
Fetch only off-diagonal elements in Cooler?

### ISSUE THREAD

**Issue by gabedolpten** [open2c/cooler#246]
Hi, let's say I am calling loops, and I have a loop at (X1, X2). AFAIK, .fetch() returns all the values between (X1, X2), which can be quite slow if X2-X1 is large. However, I am really only interested in the 10x10 window right att X1, X2 – is there a way to fetch this directly?

**Comment by Phlya** [comment]
Fetch can return any window of arbitrary shape. You can provide coordinates of both sides of the loop you are interested in. For example:
![image](https://user-images.githubusercontent.com/2895034/111209531-080bb000-85c4-11eb-93b4-be6ee3e14d84.png)

**Comment by gabedolpten** [comment]
Thank you so much Phlya!
