### ISSUE TITLE
something strange in .cool visualisation

### ISSUE THREAD

**Issue by taskina-alena** [open2c/cooler#256]
During visualization of this contacts :
chr1	55828312	chr1	56019930
chr1	55832025	chr1	56028497
chr1	55835850	chr1	56018707
chr1	55835850	chr1	56018707
chr1	55838852	chr1	56015350
chr1	55838852	chr1	56015350
chr1	55843325	chr1	56031697
chr1	55849128	chr1	56015928
chr1	55855882	chr1	56017913
chr1	55860631	chr1	56047568
we see only 2 pixels in higlass (chr1:55828312-chr1:56019930 and chr1:55835850-56018707), which have two contacts.

But if only single contacts are remained, like these:
chr1	55828312	chr1	56019930
chr1	55832025	chr1	56028497
chr1	55835850	chr1	56018707
chr1	55838852	chr1	56015350
chr1	55843325	chr1	56031697
chr1	55849128	chr1	56015928
chr1	55855882	chr1	56017913
chr1	55860631	chr1	56047568
all 8 pixels will be visible. 

P.S. galGal5 genome was used

**Comment by taskina-alena** [comment]
![i](https://user-images.githubusercontent.com/51115325/123644378-89274400-d84f-11eb-8663-a16b7f53c0ac.png)
![i2](https://user-images.githubusercontent.com/51115325/123644398-8cbacb00-d84f-11eb-82b6-dda9c20e7d37.png)

**Comment by manzt** [comment]
Closing as this is really a [HiGlass](https://github.com/higlass/higlass) issue, but it looks like the color bar in the first example is thresholded at 1 so the pixels with value <=1 are not displayed.

This can be adjusted precisely by adding `valueScaleMin` and `valueScaleMax` attributes to the view config like so:

```diff
{
	// ...
	"contents": [
		{
			"server": "//higlass.io/api/v1",
			"tilsetUid": "CQMd6V_cRw6iCI_-Unl3ZQ",
			"type": "heatmap",
			"options": {
				"minWidth": 100,
				"minHeight": 100,
				"colorbarPosition": "topRight",
				"trackBorderWidth": 0,
				"trackBorderColor": "black",
				"heatmapValueScaling": "log",
++				"valueScaeMin": 0,
++				"valueScaeMax": 2
				"extent": "full",
				"zeroValueColor": "white",
				"mousePositionColor": "black",
				"showMousePosition": false
			}
		}
	]
	// ...
}
```
