### ISSUE TITLE
Update docs and notebook tutorial

### ISSUE THREAD

**Issue by nvictus** [open2c/cooler#27]

**Comment by nvictus** [comment]
Pretty much done. Binder build is having issues, but the deploy service is constantly down anyhow.

**Comment by gfudenberg** [comment]
would be great to update cooler coarsen in cli.rst
e.g. cooler coarsen FACTOR INPUT OUTPUT
and add/link to examples as well

**Comment by gfudenberg** [comment]
would be great to update cli docs, e.g. for cooler coarsen to highlight required fields, e.g.
cooler coarsen FACTOR INPUT OUTPUT
and add/link to examples as well

**Comment by thomas-reimonn** [comment]
Closing since issue is very old and documentation has been updated several times.
