### ISSUE TITLE
getting " KeyError: 'nbins' " while running cooler dump

### ISSUE THREAD

**Issue by Giuseppe1995** [open2c/cooler#275]
Hi, I am trying to follow a [step-by-step tutorial of HiC processing](https://hms-dbmi.github.io/hic-data-analysis-bootcamp/#20) on a [example](https://github.com/open2c/pairtools#quick-example) `.bam` file (organism: _Saccharomices cerevisiae)_. I correctly performed all the steps specified in the tutorial, and when I run the command (see pag 20 of the tutorial):

`cooler dump -t pixels --header --join -r chrI out.cool` 

I get this error:

Traceback (most recent call last):
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/cooler/cli/_util.py", line 200, in decorated
    func(*args, **kwargs)
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/cooler/cli/dump.py", line 368, in dump
    bins = c.bins()[:]
  File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/cooler/api.py", line 267, in bins
    return RangeSelector1D(None, _slice, _fetch, self._info["nbins"])
KeyError: 'nbins'

I have also tried to specify regions bu with no different exit. Could you help me?
Thank you in advance, 
Guseppe

**Comment by nvictus** [comment]
Hi Giuseppe,

It sounds like something went wrong with the creation of the cooler file in the first place. Check whether inspection via `cooler attrs out.cool` or `cooler tree out.cool` gives you any output.

If there's a problem, try repeating the creation step and watch for errors. Let me know if you still have issues.

**Comment by Giuseppe1995** [comment]
In facts, when i run the previous command to generate a `.cool` file from a bgzipped `.pair` file, i get this message:

`cooler cload pairix /srv/ngs/analysis/dalteriog/reference_genomes/sc/sacCer3.reduced.chrom.sizes:5000 example.pairs.gz`

INFO:cooler.cli.cload:Using 8 cores
WARNING:py.warnings:/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/cooler/util.py:733: FutureWarning: is_categorical is deprecated and will be removed in a future version. Use is_categorical_dtype instead.
  is_cat = pd.api.types.is_categorical(bins["chrom"])

INFO:cooler.create:Creating cooler at "zzz::/"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
INFO:cooler.create:Binning chrI:0-230218|*
INFO:cooler.create:Binning chrII:0-813184|*
INFO:cooler.create:Binning chrIII:0-316620|*
INFO:cooler.create:Binning chrIV:0-770000|*
INFO:cooler.create:Binning chrIV:770000-1531933|*
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
INFO:cooler.create:Binning chrV:0-576874|*
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Binning chrVII:0-1080000|*
INFO:cooler.create:Binning chrVI:0-270161|*
[get_intv] the following line cannot be parsed and skipped: 161	+	-	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
INFO:cooler.create:Finished chrVI:0-270161|*
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
[get_intv] the following line cannot be parsed and skipped: +	UU
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
INFO:cooler.create:Binning chrVII:1080000-1090940|*
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: 159	-	-	UU
[get_intv] the following line cannot be parsed and skipped: U
INFO:cooler.create:Finished chrIII:0-316620|*
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
INFO:cooler.create:Finished chrVII:1080000-1090940|*
[get_intv] the following line cannot be parsed and skipped: U
INFO:cooler.create:Binning chrVIII:0-562643|*
[get_intv] the following line cannot be parsed and skipped: U
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
INFO:cooler.create:Binning chrIX:0-439888|*
INFO:cooler.create:Finished chrV:0-576874|*
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
INFO:cooler.create:Finished chrIV:0-770000|*
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: 3732	-	-	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Binning chrX:0-745751|*
[get_intv] the following line cannot be parsed and skipped: 	UU
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
[get_intv] the following line cannot be parsed and skipped: -	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 	UU
INFO:cooler.create:Finished chrIV:770000-1531933|*
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Binning chrXI:0-666816|*
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Finished chrIX:0-439888|*
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Finished chrVII:0-1080000|*
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Binning chrXII:0-1078177|*
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Finished chrVIII:0-562643|*
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
INFO:cooler.create:Binning chrXIII:0-924431|*
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 65870	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 
INFO:cooler.create:Binning chrXIV:0-784333|*
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
INFO:cooler.create:Binning chrXV:0-1080000|*
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 040	+	+	UU
INFO:cooler.create:Finished chrXI:0-666816|*
INFO:cooler.create:Finished chrX:0-745751|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Binning chrXV:1080000-1091291|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Finished chrXV:1080000-1091291|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Binning chrXVI:0-948066|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Binning chrM:0-85779|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Finished chrXIV:0-784333|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
INFO:cooler.create:Finished chrXIII:0-924431|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
INFO:cooler.create:Finished chrM:0-85779|*
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
INFO:cooler.create:Finished chrI:0-230218|*
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
corrupted size vs. prev_size
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 31	-	+	UU
INFO:cooler.create:Finished chrXII:0-1078177|*
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
INFO:cooler.create:Finished chrXVI:0-948066|*
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 71	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
INFO:cooler.create:Finished chrXV:0-1080000|*
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 48	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 12875	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 967	-	+	UU
[get_intv] the following line cannot be parsed and skipped: 	+	UU
[get_intv] the following line cannot be parsed and skipped: 30331	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: 7223	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	-	UU
[get_intv] the following line cannot be parsed and skipped: -	-	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 8	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 662381	+	+	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 65208	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 608952	+	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
[get_intv] the following line cannot be parsed and skipped: 	-	UU
INFO:cooler.create:Finished chrII:0-813184|*
corrupted size vs. prev_size


Moreover, it gets stuck and I must cancel with `ctrl + c`

Have I to open another issue?

**Comment by nvictus** [comment]
That looks like a `pypairix` issue, which you could report [there](https://github.com/4dn-dcic/pairix). 

Can you try using [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) instead of "pairix", which doesn't make use of an index file?

**Comment by Giuseppe1995** [comment]
using `[cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs)` I managed to do the task! thank you so much!
