### ISSUE TITLE
cootools cis_eigs error

### ISSUE THREAD

**Issue by hosseinsalari65** [open2c/cooler#276]
**Hello, 
I am using "cootools cis_eigs" for a multi-weighted .mcool file,**
"cis_eigs=cooltools.eigs_cis(clr,gc_cov,view_df=view_df,n_eigs=3)
eigenvector_track=cis_eigs[1][['chrom','start','end','E1']]"

**but I've received the following error:**

"ValueError                                Traceback (most recent call last)
~/opt/miniconda3/lib/python3.7/site-packages/cooltools/api/eigdecomp.py in eigs_cis(clr, phasing_track, view_df, n_eigs, clr_weight_name, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    383     try:
--> 384         _ = is_cooler_balanced(clr, clr_weight_name, raise_errors=True)
    385     except Exception as e:

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/lib/checks.py in is_cooler_balanced(clr, clr_weight_name, raise_errors)
    503             raise ValueError(
--> 504                 f"specified balancing weight {clr_weight_name} is not available in cooler"
    505             )

ValueError: specified balancing weight weight is not available in cooler

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-19-0e307ce2faef> in <module>
      1 import cooltools
      2 import cooltools.lib.plotting
----> 3 cis_eigs=cooltools.eigs_cis(clr,gc_cov,view_df=view_df,n_eigs=3)
      4 eigenvector_track=cis_eigs[1][['chrom','start','end','E1']]

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/api/eigdecomp.py in eigs_cis(clr, phasing_track, view_df, n_eigs, clr_weight_name, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    386         raise ValueError(
    387             f"provided cooler is not balanced or {clr_weight_name} is missing"
--> 388         ) from e
    389 
    390     # ignore diags as in cooler unless specified

ValueError: provided cooler is not balanced or weight is missing"

I
[error.pdf](https://github.com/open2c/cooler/files/8427533/error.pdf)

**I would be really appreciated it if you could help me!**

**Comment by Phlya** [comment]
Then try using the `clr_weight_name` argument with one of these values https://cooltools.readthedocs.io/en/latest/cooltools.html#cooltools.api.eigdecomp.eigs_cis

**Comment by hosseinsalari65** [comment]
Thanks a lot for your answer, but I have still the same problem!
"KeyError                                  Traceback (most recent call last)
~/opt/miniconda3/lib/python3.7/site-packages/cooltools/api/eigdecomp.py in eigs_cis(clr, phasing_track, view_df, n_eigs, clr_weight_name, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    383     try:
--> 384         _ = is_cooler_balanced(clr, clr_weight_name, raise_errors=True)
    385     except Exception as e:

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/lib/checks.py in is_cooler_balanced(clr, clr_weight_name, raise_errors)
    495         raise KeyError(
--> 496             f"clr_weight_name: {clr_weight_name} is reserved as divisive by 4DN"
    497             "cooltools supports multiplicative weights at this time."

KeyError: 'clr_weight_name: KR is reserved as divisive by 4DNcooltools supports multiplicative weights at this time.'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-38-401304208af3> in <module>
      1 import cooltools
----> 2 cis_eigs=cooltools.eigs_cis(clr,gc_cov,view_df=view_df,n_eigs=3,clr_weight_name="KR")
      3 eigenvector_track=cis_eigs[1][['chrom','start','end','E1']]

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/api/eigdecomp.py in eigs_cis(clr, phasing_track, view_df, n_eigs, clr_weight_name, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    386         raise ValueError(
    387             f"provided cooler is not balanced or {clr_weight_name} is missing"
--> 388         ) from e
    389 
    390     # ignore diags as in cooler unless specified

ValueError: provided cooler is not balanced or KR is missing"
[error (1).pdf](https://github.com/open2c/cooler/files/8429796/error.1.pdf)

**Comment by hosseinsalari65** [comment]
can you please explain how can I invert it?

**Comment by nvictus** [comment]
For example, to invert the `KR` one, open the underlying HDF5 file in append mode and save a new column:

```python

clr = cooler.Cooler(...)

with clr.open('r+') as f:
    f["bins"].create_dataset("KR_mult", data=1./f["bins/KR"][:], compression="gzip", compression_opts=6)

```

Then use the inverted weight column name `KR_mult`.

**Comment by hosseinsalari65** [comment]
Thank you very much, but I have faced to a new error:
"ValueError                                Traceback (most recent call last)
<ipython-input-72-be4d7fce03e3> in <module>
      1 import cooltools
----> 2 cis_eigs=cooltools.eigs_cis(clr,gc_cov,view_df=view_df,n_eigs=3,clr_weight_name='KR_mult')
      3 eigenvector_track=cis_eigs[1][['chrom','start','end','E1']]

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/api/eigdecomp.py in eigs_cis(clr, phasing_track, view_df, n_eigs, clr_weight_name, ignore_diags, bad_bins, clip_percentile, sort_metric, map)
    403             view_df=view_df,
    404             clr_weight_name=clr_weight_name,
--> 405             mask_bad_bins=True,
    406         )
    407 

~/opt/miniconda3/lib/python3.7/site-packages/cooltools/lib/common.py in align_track_with_cooler(track, clr, view_df, clr_weight_name, mask_bad_bins)
    296     num_assigned_bins = (clr_track["value"][valid_bins].notna()).sum()
    297     if num_assigned_bins == 0:
--> 298         raise ValueError("no track values assigned to cooler bintable")
    299     elif num_assigned_bins < 0.5 * np.sum(valid_bins):
    300         warnings.warn("less than 50% of valid bins have been assigned a value")

ValueError: no track values assigned to cooler bintable"

**Comment by Phlya** [comment]
Can you show example of the data? Or share the cooler? That sounds like there is something very weird going on with your data...

**Comment by hosseinsalari65** [comment]
The file is 2.2 Gb, can you help me how can I share the cooler?

**Comment by Phlya** [comment]
Then can you show an example of the bin and pixel tables? Some region with data.

**Comment by hosseinsalari65** [comment]
[error_2.pdf](https://github.com/open2c/cooler/files/8441780/error_2.pdf)

**Comment by hosseinsalari65** [comment]
chrom | start | end | KR | KR_mult | VC | VC_SQRT
-- | -- | -- | -- | -- | -- | --
0 | 0 | 100000 | 1.498158 | 0.667486 | 1.698446 | 1.274331
0 | 100000 | 200000 | 1.012809 | 0.987353 | 1.127751 | 1.038396
0 | 200000 | 300000 | 1.038232 | 0.963176 | 1.204253 | 1.073038
0 | 300000 | 400000 | 1.735493 | 0.576205 | 2.256540 | 1.468851
0 | 400000 | 500000 | 1.234359 | 0.810137 | 1.572974 | 1.226357
... | ... | ... | ... | ... | ... | ...
6 | 3200000 | 3300000 | 0.246146 | 4.062637 | 0.241532 | 0.360265
6 | 3300000 | 3400000 | 0.056594 | 17.669626 | 0.038061 | 0.143013
6 | 3400000 | 3500000 | 0.245734 | 4.069448 | 0.203184 | 0.330430
6 | 3500000 | 3600000 | 1.043431 | 0.958377 | 1.132682 | 0.780168
6 | 3600000 | 3667352 | 0.525111 | 1.904361 | 0.674229 | 0.601919

<p style="box-sizing: border-box; margin: 1em 0px 0px; text-align: left; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">1379 rows × 7 columns</p>

**Comment by hosseinsalari65** [comment]
Maybe it is due to chromosome name since in the genome assembly file (.fa) the chromosome names are "chr2L, chr2R, ..." but in .mcool file the names are "arm_2L, arm_2R, ...". Is there any option in cooler to change the chrom name?

**Comment by nvictus** [comment]
Yes, it's probably a mismatch between the names used in the cooler file and/or the names used in `gc_cov` and `view_df`, rather than the .fa itself.

You can rename chrom names with [this](https://cooler.readthedocs.io/en/latest/api.html#cooler.rename_chroms) function.

**Comment by Phlya** [comment]
Unless you made compartments using trans data, they are calculated for each chromosome separately. This data doesn't seem to have very strong compartments. From chromosome names I guess this is Drosophila? It's sometimes tricky to call compartments there - @agalitsyna and @golobor have some experience and might be of more help here.

**Comment by agalitsyna** [comment]
Yes, in Drosophila and other insects we usually call compartments in cis and per chromosome arms. Otherwise they are too dominated by Rabl configuration. I also use fine resolution, far less than 100 Kb, as the A compartments in Drosophila are usually smaller. I would say 5 Kb is the best choice if your data quality allows for it. Computationally it's not a big challenge, because Drosophila's genome is not very large.

**Comment by hosseinsalari65** [comment]
Thanks for your response. I did again the calculations for 8kb these are the results for the whole genome and chr2L.
![error_3](https://user-images.githubusercontent.com/54356622/162407184-43d5e628-29fe-4d8c-9aba-76b0899ad3a9.png)
![error_4](https://user-images.githubusercontent.com/54356622/162407209-76fa70fb-1b46-4987-b417-c46b8bf405db.png)

**Comment by hosseinsalari65** [comment]
Just for curiosity, could you help me with how can I dump each chromosome into a new mcool file?

**Comment by thomas-reimonn** [comment]
You can look at this discussion on how to dump each chromosome to a file: https://github.com/open2c/cooler/discussions/344#discussioncomment-6979779
