### ISSUE TITLE
bin ID error when remove chromosomes from cooler

### ISSUE THREAD

**Issue by LuJiansen** [open2c/cooler#282]
Hi, I want to remove some chromosomes (such as those non-chromosomal contigs) from cooler files, and I have tried the method described in #103 as below:

clr = cooler.Cooler('my_cooler.cool')
regex_str = '^chr'
chromsizes = clr.chromsizes.filter(regex = regex_str)
flt = cooler.binnify(chromsizes, clr.binsize)

chunksize = 1000000
spans = cooler.tools.partition(0, len(clr.pixels()), chunksize)

def chunk_generator(): 
    for i, (lo, hi) in enumerate(spans):
        print('chunk', i)
        pixels = clr.pixels()[lo:hi]
        # only necessary if there are chrM hits
        pixels = cooler.annotate(pixels, clr.bins()[['chrom']], replace=False)
        pixels = pixels[(pixels.chrom1.str.match(pat = regex_str)) & (pixels.chrom2.str.match(pat = regex_str))]
        yield pixels

cooler.io.create(<output_path>, flt, chunk_generator())

Then I got the error:

---------------------------------------------------------------------------
BadInputError                             Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 cooler.io.create(output, flt, chunk_generator())

File /mnt/h/wsl/miniconda3/envs/nanopore/lib/python3.8/site-packages/cooler/io.py:37, in create(*args, **kwargs)
     29 warnings.warn(
     30     "`cooler.io.create()` is deprecated in 0.8, will be removed in 0.9. "
     31     "Use `cooler.create_cooler()` with ordered=True instead.",
     32     category=FutureWarning,
     33     stacklevel=2,
     34 )
     35 from .create import create
---> 37 return create(*args, **kwargs)

File /mnt/h/wsl/miniconda3/envs/nanopore/lib/python3.8/site-packages/cooler/create/_create.py:643, in create(cool_uri, bins, pixels, columns, dtypes, metadata, assembly, symmetric_upper, mode, h5opts, boundscheck, triucheck, dupcheck, ensure_sorted, lock, append, append_scool, scool_root_uri, **kwargs)
    641 logger.info("Writing pixels")
    642 target = posixpath.join(group_path, "pixels")
--> 643 nnz, ncontacts = write_pixels(
    644     file_path, target, meta.columns, iterable, h5opts, lock
    645 )
    647 # Write indexes
    648 with h5py.File(file_path, "r+") as f:

File /mnt/h/wsl/miniconda3/envs/nanopore/lib/python3.8/site-packages/cooler/create/_create.py:214, in write_pixels(filepath, grouppath, columns, iterable, h5opts, lock)
    212 nnz = 0
    213 total = 0
--> 214 for i, chunk in enumerate(iterable):
    216     if isinstance(chunk, pd.DataFrame):
    217         chunk = {k: v.values for k, v in six.iteritems(chunk)}

File /mnt/h/wsl/miniconda3/envs/nanopore/lib/python3.8/site-packages/cooler/create/_ingest.py:351, in _validate_pixels(chunk, n_bins, boundscheck, triucheck, dupcheck, ensure_sorted)
    349     is_excess = (chunk["bin1_id"] >= n_bins) | (chunk["bin2_id"] >= n_bins)
    350     if np.any(is_excess):
--> 351         raise BadInputError(
    352             "Found a bin ID that exceeds the declared number of bins. "
    353             "Check whether your bin table is correct."
    354         )
    356 if triucheck:
    357     is_tril = chunk["bin1_id"] > chunk["bin2_id"]

BadInputError: Found a bin ID that exceeds the declared number of bins. Check whether your bin table is correct.
---------------------------------------------------------------------------

Since those bins from non-chromosome contig were in the head of bins list, some bin ID in the remained bins will exceed the declared number of bins in the filtered bin table.
So, is there any method to rename the bin IDs in cooler files? or any other suggestions?

**Comment by LuJiansen** [comment]
the question could be solved by using cooler dump and load with a new chromsize file.

cooler dump --join /path/to/input.cool | cooler load --format bg2 /path/to/new/chromsize.txt:<resolution> - /path/to/output.cool

**Comment by Jelena4** [comment]
When using:
cooler dump --join /path/to/input.cool | cooler load --format bg2 /path/to/new/chromsize.txt: - /path/to/output.cool

cooler load report an error:
ValueError: Expected integer binsize argument (bp), got ""

If I specify the binsize:
cooler dump --join /path/to/input.cool | cooler load --format bg2 /path/to/new/chromsize.txt:100000 - /path/to/output.cool

I get a different error:
pandas.errors.ParserError: Too many columns specified: expected 2 and found 1

Am I doing something wrong?
