### ISSUE TITLE
ValueError: no track values assigned to region

### ISSUE THREAD

**Issue by Jelena4** [open2c/cooler#290]
Hi, I get an error when running cooltools.saddle:
ValueError: no track values assigned to region

My cooler has extra scaffolds, some of which contain no interactions. How can I fix this? Thank you

**Comment by agalitsyna** [comment]
Hi, @Jelena4, this is not cooler but cooltools behavior. What version of cooltools do you use?
 
We recently introduced parameter `drop_track_na` which allows you to ignore missing chromosomes in the track. 
You can find more details here: https://github.com/open2c/cooltools/pull/387 and https://github.com/open2c/cooltools/pull/360

I would start by installing the most recent GitHub version of cooltools and repeating the same processing steps. 
If the problem persists, please, provide the chromosomes sizes in you cooler and track dataframe that you align!

**Comment by Jelena4** [comment]
cooltools.__version__
'0.5.1'

<img width="924" alt="Screen Shot 2022-09-27 at 2 27 23 PM" src="https://user-images.githubusercontent.com/54960484/192617893-b0b4d3f1-eb83-4b92-a11f-85c33720f3a1.png">

**Comment by Jelena4** [comment]
I used a genome "pooled" genome to check for contamination and also other scaffolds, so in addition to mm10 it has S. cerevisiae, D. melanogaster, MMTV and 601 chromosomes and contigs. It seems that the list of chromosomes is identical in clr and cvd. I cannot call the drop_tracks_na parameter though.

<img width="782" alt="Screen Shot 2022-09-27 at 2 42 31 PM" src="https://user-images.githubusercontent.com/54960484/192620616-6ee1d67c-0bf3-423c-bc6a-139c93e7add6.png">

**Comment by Jelena4** [comment]
<img width="843" alt="Screen Shot 2022-09-27 at 2 51 05 PM" src="https://user-images.githubusercontent.com/54960484/192622335-e50f28fb-6d1b-4a4a-9b96-db6084dad34a.png">

**Comment by agalitsyna** [comment]
@Jelena4 Your version of cooltools is outdated.

**Comment by Jelena4** [comment]
Thank you, reinstalled from github and now it works!
