### ISSUE TITLE
RuntimeError: No reference sequences found.

### ISSUE THREAD

**Issue by TakatoG** [open2c/cooler#294]
Hi! I got the error message when I typed following command.
cooler cload pairix mm10.chrom.sizes:250000 output.pairs.gz output.cool
and then,
RuntimeError: No reference sequences found.

Could you teach me why this happen?

**Comment by thomas-reimonn** [comment]
Sorry, but there's not enough information to diagnose. Please re-open and provide input files and the command if this is still an issue.
