### ISSUE TITLE
Use of `cooler load` with per-resolution BG2 data may overwrite mcool container at each resolution

### ISSUE THREAD

**Issue by alexpreynolds** [open2c/cooler#296]
I am using the documentation on HiGlass as a reference for making a test `mcool` file: https://docs.higlass.io/data_preparation.html#cooler-files

I have a series of commands like these to make that test file, one command for each resolution level:

```
% cooler load -f bg2 --no-symmetric-upper chromsizes.txt:9 bg2.signal.10.txt bg2.signal.mcool::resolutions/9
% cooler load -f bg2 --no-symmetric-upper chromsizes.txt:18 bg2.signal.9.txt bg2.signal.mcool::resolutions/18
...
% cooler load -f bg2 --no-symmetric-upper chromsizes.txt:2304 bg2.signal.2.txt bg2.signal.mcool::resolutions/2304
```

(Each of `bg2.signal.*.txt` can be made into an individual `cool` file, which can be investigated and render a heatmap, so I believe them to each be formatted correctly.)

The `bg2.signal.mcool` file only appears to contain data for resolution 2304 (the last BG2 table loaded in: `bg2.signal.2.txt`). 

If I try to get information for any other resolution, I get `KeyError` exceptions, e.g. for bin size 18:

```
% cooler info bg2.signal.mcool::resolutions/18
...
KeyError: "Unable to open object (object '18' doesn't exist)"
KeyError: "No cooler found at: bg2.signal.mcool. Coolers found in ['/resolutions/2304']. Use '::' to specify a group path"
```

Investigating this and a third-party `mcool` file with HDFView shows that my file `bg2.signal.mcool` lacks root attributes from the [schema](https://cooler.readthedocs.io/en/latest/schema.html#multi-resolution), along with the other resolutions.

I'm wondering if I'm missing something here, but I'm not sure what. Is the above a correct procedure for generating a multi-resolution cooler file?

**Comment by nvictus** [comment]
Two issues here:

1. Append-mode loading: I'm able to reproduce `cooler load` doing a hard write and not an append, which I don't think was intended behavior, so it should be investigated and fixed.

Temporary solution:

Load the resolutions into separate files. You can use `cooler cp` and `cooler mv` to combine them into a single file

2. Root-level metadata: in line with typical usage, mcools are normally produced by applying `cooler zoomify` on a single resolution, and will add the root-level attributes for the whole file. For such a manually constructed mcool, you will need to add those attributes manually, but there are only three.

Solution:

```python
with h5py.File(filepath, "a") as f:
    f["format"] = "HDF5:MCOOL"
    f["format-version"] = 2
    f["bin-type"] = "fixed"
```

**Comment by nvictus** [comment]
I forgot to mention that you have full flexibility with the API function, if you prefer: https://cooler.readthedocs.io/en/latest/api.html#cooler.create_cooler

**Comment by alexpreynolds** [comment]
I also took a look at some other `mcool` files and the schema, and used something like the following to build it via `h5py`:

```
output_mcool_fn = os.path.join(data_dir, 'mysignal.mcool')
with h5py.File(output_mcool_fn, 'w') as output_mcool_h5:
    output_mcool_h5.attrs['format'] = 'HDF5::MCOOL'
    output_mcool_h5.attrs['format-version'] = 2
    output_mcool_h5.attrs['bin-type'] = 'fixed'
    all_resolutions = output_mcool_h5.create_group('resolutions')
    for resolution_idx, resolution_val in enumerate(resolutions):
        bin_size = bin_size_fn(resolution_val)
        per_resolution = all_resolutions.create_group(str(bin_size))
        input_bg2_cool_fn =  os.path.join(data_dir, 'mysignal.{}.cool'.format(resolution_val))
        if not os.path.exists(input_bg2_cool_fn):
            raise FileNotFoundError("Cannot find per-resolution BG2 cooler file")
        with h5py.File(input_bg2_cool_fn, 'r') as input_bg2_cool_h5:
            per_resolution.attrs['bin-size'] = input_bg2_cool_h5.attrs['bin-size']
            per_resolution.attrs['bin-type'] = input_bg2_cool_h5.attrs['bin-type']
            per_resolution.attrs['creation-date'] = input_bg2_cool_h5.attrs['creation-date']
            per_resolution.attrs['format'] = input_bg2_cool_h5.attrs['format']
            per_resolution.attrs['format-url'] = input_bg2_cool_h5.attrs['format-url']
            per_resolution.attrs['format-version'] = input_bg2_cool_h5.attrs['format-version']
            per_resolution.attrs['generated-by'] = input_bg2_cool_h5.attrs['generated-by']
            per_resolution.attrs['genome-assembly'] = input_bg2_cool_h5.attrs['genome-assembly']
            per_resolution.attrs['metadata'] = input_bg2_cool_h5.attrs['metadata']
            per_resolution.attrs['nbins'] = input_bg2_cool_h5.attrs['nbins']
            per_resolution.attrs['nchroms'] = input_bg2_cool_h5.attrs['nchroms']
            per_resolution.attrs['nnz'] = input_bg2_cool_h5.attrs['nnz']
            per_resolution.attrs['storage-mode'] = input_bg2_cool_h5.attrs['storage-mode']
            per_resolution.attrs['sum'] = input_bg2_cool_h5.attrs['sum']
            for input_bg2_cool_h5_group in input_bg2_cool_h5.keys():
                input_bg2_cool_h5[input_bg2_cool_h5_group].copy(input_bg2_cool_h5[input_bg2_cool_h5_group], per_resolution)
```

I'm not an `h5py` expert so there may be a much cleaner or more Pythonic way of doing this. 

But I think this should get me to an mcool file I can later use with HiGlass, or close enough to tweak.

The reason for manual appending as opposed to `cooler zoomify` is that I need to apply custom aggregation at each resolution level — basically, applying the method I am using to build a fully-packed Hilbert curve of data at each order. I don't think the method applied via `zoomify` would work for scaling Hilbert curves.

Thanks for pointing out the Python API side. When using `cooler.create_cooler`, would I specify the resolution level in the URI (as is done for the CLI method), or would I use another parameter?

**Comment by nvictus** [comment]
An explicit `--append` option is now exposed to the command line #308
