### ISSUE TITLE
Differentiate src open mode when copying

### ISSUE THREAD

**Issue by bernt-matthias** [open2c/cooler#299]
Opening the src fine `r+` should only be used if src is actually written to

https://github.com/open2c/cooler/blob/987e87dd357c99a0a070b8a25cb7aaef86f1655c/cooler/fileops.py#L277

**Comment by nvictus** [comment]
Thanks for catching this. The reason it's like that is that the operation supports copying and moving within the same file. However, the code could be made more granular to use `r` when appropriate. Will push a fix.

**Comment by bernt-matthias** [comment]
Wonderful.
