### ISSUE TITLE
Can't install cooler & cooltools

### ISSUE THREAD

**Issue by gdolsten** [open2c/cooler#311]
HI, I am trying to install cooltools. When I run it, I get the following error:

  File "/Genomics/argo/users/gdolsten/.conda/envs/mamba/envs/open2c/lib/python3.9/site-packages/cooltools/lib/numutils.py", line 784, in <module>
    class LazyToeplitz(cooler.core._IndexingMixin):
AttributeError: module 'cooler.core' has no attribute '_IndexingMixin'

Do you know where this is coming from?

**Comment by nvictus** [comment]
I'm guessing you just installed it? This is probably coming from the latest cooler release yesterday and there are a couple breaking changes in cooltools because it relies on some internal APIs. 

In short, can you try installing `cooler<0.9` or `0.8.11` and see if it works?

**Comment by Phlya** [comment]
This is now fixed by @nvictus! Just installing the new cooltools release should help.
