### ISSUE TITLE
Conda installation: Solving environment: ...NOT working...

### ISSUE THREAD

**Issue by togop** [open2c/cooler#316]
Hi,

I'm trying to install the cooler Python package in a new environment (Python 3.10.8) for automated tests, but the installation is not crashing.
Here more details before installation:
 - conda 22.11.1
 -  --add channels bioconda conda-forge
 - conda install -y -q numpy pandas matplotlib scipy dask h5py

The error I'm getting after trying to install it
$ conda install -y -q cooler
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... WARNING: Error while executing file based variables removal script  error=context canceled job=1 project=0
ERROR: Job failed: execution took longer than 30m0s seconds
FATAL: execution took longer than 30m0s seconds    
```
The same error comes trying with fixed older version 
$ conda install -y -q "cooler=0.8.11"

I hope you can help me to solve this issue or find if there is an installation bug.

Best regards,
Todor

**Comment by nvictus** [comment]
If it's not an actual error, just that conda's sat solver is behaving really slow, I'd give [mamba](https://mamba.readthedocs.io/en/latest/installation.html) a try.

**Comment by nvictus** [comment]
Alternatively, you can still create your environment with conda and install cooler with `pip`.

**Comment by togop** [comment]
Thanks a lot. The mamba works best.
