### ISSUE TITLE
Identical pairs with different counts given by cooler dump

### ISSUE THREAD

**Issue by ziyin96** [open2c/cooler#319]
Hi, 

I used `cooler dump` (cooler version 0.9.1) to dump the balanced contact frequency of a certain viewpoint under 25-kb resolution.
The mcool file was downloaded from 4DN.

```
cooler dump --join --fill-lower --balanced -r chr3:34650000-34675000 -r2 1:160039680 \
         4DNFIC21MG3U.mcool::/resolutions/25000 \
         > vp.txt
```

All the results looks right but I found 2 lines (the 807th and 808th) that give me identical coordinate pairs but different counts.
```
chr3    34650000        34675000        chr3    24975000        25000000        1       2.09417e-05
chr3    34650000        34675000        chr3    24975000        25000000        2       4.18834e-05
```

How does this happend and how should I deal with these two lines? 

[vp.txt](https://github.com/open2c/cooler/files/11109137/vp.txt)

**Comment by robomics** [comment]
Hi,

this seems the same issue outlined [here](https://github.com/robomics/20221129_4dnucleome_bug_report).

I reported this issue to 4DNucleome back in Nov 2022. They acknowledged the issue and are looking for solutions.

Luckily the base resolution does not seem to be affected by this issue, so a possible workaround is to re-create the `.mcool` by running `cooler zoomify` on the base resolution.

**Comment by Phlya** [comment]
I can't find it right now, but I think this was fixed in a recent cooler release. Assuming the file was created using an older cooler version, you can re-zoomify it from the base resolution as suggested above, using the latest cooler version.

**Comment by ziyin96** [comment]
Thanks a lot! Re-zoomify the mcool file does work for me!
