### ISSUE TITLE
cooler.create_cooler ERROR

### ISSUE THREAD

**Issue by shinohara-xiao** [open2c/cooler#321]
Hi,author !
When I  use cooler.create_cooler to generate cooler file using bins and pixels files, I successfully generate cooler file with following files:

part of my bins file
![image](https://user-images.githubusercontent.com/76273145/231054189-9b0e375b-414a-4680-a480-cf25d742f529.png)
part of my pixels file
![image](https://user-images.githubusercontent.com/76273145/231054273-4f86d1d7-655e-4d91-ad08-c8ed60417134.png)

However, when I **add "weight" columns to the bins file**, I got an error like this:

KeyError                                  Traceback (most recent call last)
File [~/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/cooler/core.py:146](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/lanec2_home/zhangx/single-cell/~/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/cooler/core.py:146), in put(grp, df, lo, store_categories, h5opts)
    145 try:
--> 146     dset = grp[field]
    147 except KeyError:

File h5py[/_objects.pyx:54](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/_objects.pyx:54), in h5py._objects.with_phil.wrapper()

File h5py[/_objects.pyx:55](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/_objects.pyx:55), in h5py._objects.with_phil.wrapper()

File [~/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/h5py/_hl/group.py:328](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/lanec2_home/zhangx/single-cell/~/.conda/envs/schic-scvi-3d/lib/python3.8/site-packages/h5py/_hl/group.py:328), in Group.__getitem__(self, name)
    327 elif isinstance(name, (bytes, str)):
--> 328     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    329 else:

File h5py[/_objects.pyx:54](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/_objects.pyx:54), in h5py._objects.with_phil.wrapper()

File h5py[/_objects.pyx:55](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/_objects.pyx:55), in h5py._objects.with_phil.wrapper()

File h5py[/h5o.pyx:190](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/h5o.pyx:190), in h5py.h5o.open()

KeyError: "Unable to open object (object 'weight' doesn't exist)"

During handling of the above exception, another exception occurred:
...
File h5py[/h5t.pyx:1725](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/h5t.pyx:1725), in h5py.h5t.py_create()

File h5py[/h5t.pyx:1538](https://vscode-remote+ssh-002dremote-002bsysu.vscode-resource.vscode-cdn.net/h5t.pyx:1538), in h5py.h5t._c_string()

ValueError: Size must be positive (size must be positive)

and part of my bins file is :
![image](https://user-images.githubusercontent.com/76273145/231054533-f2e12051-de85-4e8e-b75b-98fbc4249055.png)

How can I solve this problem? 
Sorry to bother and thank you very much !

**Comment by nvictus** [comment]
The `put` function is not part of cooler's public API and you haven't shown how you used it, so I can't diagnose. 

If you want to append a 1D array or pandas Series as a column to a table, you can use HDF5 directly as shown in [this answer](https://github.com/open2c/cooler/discussions/392#discussioncomment-8576180).

You need to make sure that the length of the array matches the other columns of the table.
