### ISSUE TITLE
Discrepancy in Summation Results When Fetching Matrix Data with Different Methods

### ISSUE THREAD

**Issue by skelviper** [open2c/cooler#354]
Hello,

I am an avid user of the 'cooler' package, and it has been instrumental in my bioinformatics workflow. Recently, I have encountered an inconsistency that is perplexing and has impacted my data processing pipeline.

Issue Description:
I converted a 'pairs' file into a 5k 'cool' format and subsequently applied 'zoomify' to produce a 'test.mcool' file. Upon using the Python API to analyze the data, I discovered a discrepancy between the summation results of matrix counts, depending on the method employed.

When I use:
clr.matrix(balance=False, as_pixels=True, join=True).fetch("chrX(mat)")["count"].values.sum()

I get a result of 6213, which aligns with the number of rows in my original 'pairs' file.

However, with:

clr.matrix(balance=False).fetch("chrX(mat)").sum()

I receive a result of 9975, which does not make sense in the context of my data.

System Information:
Cooler version: cooler, version 0.8.11
Operating system: Centos7
Python version: Python 3.8.12

I would greatly appreciate your insight into why this inconsistency occurs and how I might resolve or circumvent it. This issue has not only become an obstacle for me, but it also poses a risk of other 'cooler' users inadvertently obtaining incorrect results.

I am looking forward to your response and am willing to provide any additional information or perform further testing as required.
[test.mcool.zip](https://github.com/open2c/cooler/files/13184842/test.mcool.zip)

Best regards,
Zhiyuan Liu

**Comment by nvictus** [comment]
The "as-pixels" selector `clr.matrix(balance=False, as_pixels=True)` only returns the **upper triangle portion** of the global contact matrix, including the main diagonal, which will correspond to what you see in a pairs file.

`clr.matrix(balance=False)` returns a numpy array of the full contact matrix, including the lower triangle portion as well.

You can validate this:

```python
clr = cooler.Cooler("test.mcool::resolutions/5000")

df = clr.matrix(balance=False, as_pixels=True).fetch("chrX(mat)")
diag_sum = df[df['bin1_id'] == df['bin2_id']]['count'].sum()
upper_sum = df[df['bin1_id'] != df['bin2_id']]['count'].sum()
array_sum = clr.matrix(balance=False).fetch("chrX(mat)").sum()

assert(array_sum == diag_sum + 2*upper_sum)
```

Or by visualizing your results.

**Comment by skelviper** [comment]
Oh, I forgot about the issue with the upper triangle, that was really silly of me. Initially, when I saw that the matrix sum was different under different resolutions, I thought there would be some problems. Thank you so much for your help!
