### ISSUE TITLE
Cooler digest with 2 restriction enzymes

### ISSUE THREAD

**Issue by ddepierre** [open2c/cooler#358]
Hi cooler people, 

Is it possible to use cooler digest with 2 restriction enzymes?

Something like:
`
cooler digest --rel-ids 0 --out mm10_DpnII_DdeI_restriction_sites_cooler_digest.bed chrNameLength.txt mm10.chroms.all.fa DdeI, DpnII`

or an alternative with cooltools genome digest like:
`cooltools genome digest chrNameLength.txt mm10.chroms.all.fa DdeI,DpnII`

Thanks for support, 
David

**Comment by nvictus** [comment]
`cooler digest` does not support multiple enzymes, though this is something we can add, since it uses biopython under the hood which can do this.

>Alternatively, can you confirm I can do it with
If I understand correctly what GRanges `disjoin` is doing (cutting out overlapping ranges as separate intervals), then, yes, this makes sense!
