### ISSUE TITLE
cooler cload pairs memory usage error

### ISSUE THREAD

**Issue by sfh1111** [open2c/cooler#412]
Hi,

Thanks for super cool tool:)
I am trying to use cooler cload pairs on 230Gb pairs.gz file with the following command: cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 --assembly mm10 --temp-dir tmp mm10_genome.sizes.200 xxx.nodups.pairs.gz xxx.cool . the tmpxxxx.cool file is created normally but when it writs the data to the final cool file it collapses and gives the following error: TERM_MEMLIMIT: job killed after reaching LSF memory usage limit. Exited with exit code 137. 
I have already tried to give this job more memory but it always stop at the same point when it start writing to the cool file and then stop after 4000Kb.
Any suggestions?

**Comment by nvictus** [comment]
This should be fixed in v0.10 via https://github.com/open2c/cooler/pull/408. Can you give it a try?

**Comment by nvictus** [comment]
Please re-open if this hasn't been fixed.

**Comment by sfh1111** [comment]
Hi,
Thanks for the reply. I have actually made a bypass- I have used smaller
files to create pairs file and merged the files after I created the cool
files.
Thanks for your help and for this useful tool,
Shdema
