### ISSUE TITLE
yo_mama so FAT she cannot fit inside a .cool file

### ISSUE THREAD

**Issue by cd-mcfarland** [open2c/cooler#416]
Hi @nvictus, I have a Hi-C dataset formatted in a File Allocation Table (FAT). `yo_mama` is so large, she cannot be partitioned by FAT32. Perhaps a more modern file format is needed? `yo_mama` is so old, her timestamp precedes the Proleptic Gregorian Calendar.

**Comment by nvictus** [comment]
Ouch, that's quite a burn! I'd recommend throwing a beefy big mac (M2 or M3 pro) at `yo_mama`. Though, if `yo_mama` is as expansive as you suggest, you might want to consider a server farm for containment. 

Closing, though, as we have no plans to support bigger byte architectures at this time.
