### ISSUE TITLE
Plotting HiC Matrix only shows a diagonal

### ISSUE THREAD

**Issue by arodel21** [open2c/cooler#429]
Hello,

I am trying to plot a HiC matrix -- that I downloaded from a public repository -- in 5kb resolution using Python and the cooler module. But the plot only **shows a diagonal**... 

My code is the following

```
matrix="hic_file.mcool::resolutions/5000"
clr = cooler.Cooler(matrix)
f, ax = plt.subplots(figsize=(7,6))
im = ax.matshow((clr.matrix(balance=False).fetch('chr1')),vmax=500);
plt.colorbar(im ,fraction=0.046, pad=0.04, label='raw counts')
plt.savefig("hic_heatmap_chr1.png")
```

I didn't do any processing on the mcool file... Is there a common reason why this would happen?

Thanks in advance.
Best wishes.

**Comment by Phlya** [comment]
My guess is that you need to log-scale the data...

**Comment by arodel21** [comment]
Thank you so mujch for the quick reply.

This is what I had before normalizing 

![hic_heatmap_chr2](https://github.com/user-attachments/assets/e8e668d2-ac14-471c-a016-7a28b1f8fa4f)

And this is after normalizing...

![hic_heatmap_norm_chr2](https://github.com/user-attachments/assets/a49cbbb3-1c81-4a49-b6d6-145e5bf50856)

I am not sure how to interpret it

**Comment by Phlya** [comment]
Your data are very sparse at this resolution, hard to see any patterns. But technically the plotting is working as expected...

**Comment by arodel21** [comment]
@Phlya Thank you so much for your help and advice!

**Comment by Phlya** [comment]
Happy to help!
