### ISSUE TITLE
KeyError with fetch 

### ISSUE THREAD

**Issue by MuhundenJ** [open2c/cooler#435]
Hi !

I'm fairly new to cooler/cooltools and would like to get some advice on this issue. I have some .cool files that I would like to visualize using cooltools. The file appears to load and behave correctly but I run into an invalid KeyError when trying to extract matrix data using fetch() for any specific chromosome based on its name for visualisation. See code and output below

```
# import standard python libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os
import cooltools 
import cooler
```

```
data_dir= '../cool-files/'
clr = cooler.Cooler(f'{data_dir}/MJ21_2_combined.1000_balanced.cool')
```

```
print(clr.chromnames)   ### chromNames correspond to our individual fosmids/BACs

print(clr.chromsizes)

print(clr.binsize)
```

>['chrX:389304-431578', 'chrX:795762-831457', 'chrX:1616483-1666328', 'chrX:2135290-2166685', 'chrX:2685715-2721010', 'chrX:3667733-3708827', 'chrX:3704259-3739628', 'chrX:3724647-3755934', 'chrX:5318986-5352179', 'chrX:7035928-7072577', 'chrX:7053320-7095787', 'chrX:8909920-8947159', 'chrX:10742683-10778978', 'chrX:10778059-10813017', 'chrX:10806687-10840288', 'chrX:10832134-10868578', 'chrX:11124685-11157816', 'chrX:13263400-13305203', 'chrX:13312144-13347266', 'chrX:14500243-14533957', 'chrX:15252394-15293829', 'chrX:16217642-16258872', 'chrX:16900768-16933931', 'chrX:16987106-17017397', 'chrX:18411455-18447585', 'chrX:18647514-18690910', 'chrX:19017578-19051456', 'chrX:19681040-19717450', 'chrX:19725749-19763469', 'chrX:21036774-21075498', 'chr2R:9783303-9864769', 'chr2R:9861736-9954592', 'chr2R:9937874-10035582', 'chr2R:10034493-10133457']
name
chrX:389304-431578         42275
chrX:795762-831457         35696
chrX:1616483-1666328       49846
chrX:2135290-2166685       31396
chrX:2685715-2721010       35296
chrX:3667733-3708827       41095
chrX:3704259-3739628       35370
chrX:3724647-3755934       31288
chrX:5318986-5352179       33194
chrX:7035928-7072577       36650
chrX:7053320-7095787       42468
chrX:8909920-8947159       37240
chrX:10742683-10778978     36296
chrX:10778059-10813017     34959
chrX:10806687-10840288     33602
chrX:10832134-10868578     36445
chrX:11124685-11157816     33132
chrX:13263400-13305203     41804
chrX:13312144-13347266     35123
chrX:14500243-14533957     33715
chrX:15252394-15293829     41436
chrX:16217642-16258872     41231
chrX:16900768-16933931     33164
chrX:16987106-17017397     30292
chrX:18411455-18447585     36131
chrX:18647514-18690910     43397
chrX:19017578-19051456     33879
chrX:19681040-19717450     36411
chrX:19725749-19763469     37721
chrX:21036774-21075498     38725
chr2R:9783303-9864769      81467
chr2R:9861736-9954592      92857
chr2R:9937874-10035582     97709
chr2R:10034493-10133457    98965
Name: length, dtype: int32
1000

The structure of the dataset appears correct. Further confirmed by looking at the associated matrix.

```
clr.matrix(balance=False,as_pixels=True,join=True)[:]
```
>

chrom1 | start1 | end1 | chrom2 | start2 | end2 | count
-- | -- | -- | -- | -- | -- | --
chrX:389304-431578 | 2000 | 3000 | chrX:389304-431578 | 2000 | 3000 | 1
chrX:389304-431578 | 7000 | 8000 | chrX:389304-431578 | 7000 | 8000 | 1
chrX:389304-431578 | 14000 | 15000 | chrX:389304-431578 | 14000 | 15000 | 1
chrX:389304-431578 | 40000 | 41000 | chrX:389304-431578 | 40000 | 41000 | 1
chrX:795762-831457 | 0 | 1000 | chrX:795762-831457 | 0 | 1000 | 6697
... | ... | ... | ... | ... | ... | ...
chr2R:10034493-10133457 | 96000 | 97000 | chr2R:10034493-10133457 | 97000 | 98000 | 963
chr2R:10034493-10133457 | 96000 | 97000 | chr2R:10034493-10133457 | 98000 | 98965 | 2
chr2R:10034493-10133457 | 97000 | 98000 | chr2R:10034493-10133457 | 97000 | 98000 | 3545
chr2R:10034493-10133457 | 97000 | 98000 | chr2R:10034493-10133457 | 98000 | 98965 | 905
chr2R:10034493-10133457 | 98000 | 98965 | chr2R:10034493-10133457 | 98000 | 98965 | 3506

<p style="text-align: left; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.87); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">37261 rows × 7 columns</p>

Now try to fetch contacts associated with any particular region (based on the chromName) 

```
clr.matrix(balance=False,as_pixels=True).fetch('chr2R:10034493-10133457')
```

Full Error message

>KeyError                                  Traceback (most recent call last)
File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/core/indexes/base.py:3803, in Index.get_loc(self, key, method, tolerance)
   3802 try:
-> 3803     return self._engine.get_loc(casted_key)
   3804 except KeyError as err:
File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()
File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()
File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()
File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

>KeyError: 'chr2R'

>The above exception was the direct cause of the following exception:
KeyError                                  Traceback (most recent call last)
File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/cooler/util.py:172, in parse_region(reg, chromsizes)
    171 try:
--> 172     clen = chromsizes[chrom] if chromsizes is not None else None
    173 except KeyError as e:

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/core/series.py:981, in Series.__getitem__(self, key)
    980 elif key_is_scalar:
--> 981     return self._get_value(key)
    983 if is_hashable(key):
    984     # Otherwise index.get_value will raise InvalidIndexError

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/core/series.py:1089, in Series._get_value(self, label, takeable)
   1088 # Similar to Index.get_value, but we do not fall back to positional
-> 1089 loc = self.index.get_loc(label)
   1090 return self.index._get_values_for_loc(self, loc, label)

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/pandas/core/indexes/base.py:3805, in Index.get_loc(self, key, method, tolerance)
   3804 except KeyError as err:
-> 3805     raise KeyError(key) from err
   3806 except TypeError:
   3807     # If we have a listlike key, _check_indexing_error will raise
   3808     #  InvalidIndexError. Otherwise we fall through and re-raise
   3809     #  the TypeError.

>KeyError: 'chr2R'
The above exception was the direct cause of the following exception:
ValueError                                Traceback (most recent call last)
Cell In[24], line 1
----> 1 clr.matrix(balance=False,as_pixels=True).fetch('chr2R:10034493-10133457')

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/cooler/core/_selectors.py:185, in RangeSelector2D.fetch(self, *args, **kwargs)
    183 def fetch(self, *args, **kwargs) -> Any:
    184     if self._fetch is not None:
--> 185         i0, i1, j0, j1 = self._fetch(*args, **kwargs)
    186         return self._slice(self.field, i0, i1, j0, j1)
    187     else:

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/cooler/api.py:395, in Cooler.matrix.<locals>._fetch(region, region2)
    393 if region2 is None:
    394     region2 = region
--> 395 region1 = parse_region(region, self._chromsizes)
    396 region2 = parse_region(region2, self._chromsizes)
    397 i0, i1 = region_to_extent(grp, self._chromids, region1, self.binsize)

>File /work/project/becbec_005/Hi_C/HiC/lib/python3.8/site-packages/cooler/util.py:174, in parse_region(reg, chromsizes)
    172     clen = chromsizes[chrom] if chromsizes is not None else None
    173 except KeyError as e:
--> 174     raise ValueError(f"Unknown sequence label: {chrom}") from e
    176 start = 0 if start is None else start
    177 if end is None:
ValueError: Unknown sequence label: chr2R 

I'm not quite sure why my input chromosome name gets stripped down to just 'chr2R' as the Key. Or is the source of the problem elsewhere? Please let me know if you need more information.

Cheers,
Jay

**Comment by MuhundenJ** [comment]
I eventually figured out that the input for fetch function is a tuple of the format (chromName,start,end), a bit different from example shown in https://cooltools.readthedocs.io/en/latest/notebooks/viz.html

**Comment by nvictus** [comment]
Oh, interesting edge case revealed! Your fosmid contig names contain a colon, and the UCSC-style query parser assumes contig names do not contain colons (it interprets your queries as ranges). The alternative tuple syntax will still work for you, as you have seen. 

Question is whether we want to disallow colons in chrom names entirely and enforce it. Is it common to name fosmid/BACs this way?
