### ISSUE TITLE
Normalization of non-fixed bin sizes matrix

### ISSUE THREAD

**Issue by XunuoZhu** [open2c/cooler#437]
Continue the discussion in #104 , I wonder how to normalize the matrix with non-fixed bin sizes like this:
```
chr	start	end
chr1	104896	105048
chr1	138866	139134
chr1	180743	180904
chr1	181014	181237
chr1	181289	181639
chr1	267925	268171
chr1	271226	271468
```
Just to make sure, cooler already supports fetching contact matrices based on variable bin-size, right?

**Comment by nvictus** [comment]
You can normalize the variable binsize data just like a usual contact map by calculating normalization factors $w_i$ associated with each bin $i$, such that $N_{ij} = A_{ij}w_{i}w_{j}$. For matrix balancing, this would give each custom bin equal "visibility". Depending on your research question, this may be appropriate. If you want to normalize genomic coverage, then you are better off binning the data uniformly.

> Just to make sure, cooler already supports fetching contact matrices based on variable bin-size, right?

Yes.
