### ISSUE TITLE
after cooler balance the weight is "NaN"

### ISSUE THREAD

**Issue by zcq23** [open2c/cooler#439]
Hi, my clr file doesn't have the weight column,
>>> clr = cooler.Cooler("/data1/article/10/GSM7682291_GM12878_cell_020.cool")
>>> bins = clr.bins()[:]
>>> print(bins)
      chrom     start       end
0         M         0     16569
1         1         0    100000
2         1    100000    200000
3         1    200000    300000
4         1    300000    400000

so I try to run " cooler balance /data1/article/10/GSM7682291_GM12878_cell_020.cool" and the result is :
      chrom     start       end  weight
0         M         0     16569     NaN
1         1         0    100000     NaN
2         1    100000    200000     NaN
3         1    200000    300000     NaN
4         1    300000    400000     NaN

it's so strange that all the weight is "NaN", and the file "GSM7682291_GM12878_cell_020.cool" was downloaded from [GSE240128](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE240128) and coverted the .hic to .cool by 
"for file in *.hic; do
    if [ -f "$file" ]; then
        PREFIX=$(basename "$file" .hic)
        hic2cool convert -r 100000 "$file" "${PREFIX}.cool"
    fi
done"

I don't know what's wrong with it because no error happened during the above process, indeedly hope for your reply😭many many thanks!!!

**Comment by Phlya** [comment]
Are you sure they are all NaN, and not just the first few? Usually the beginning of chromosomes are repetitive and masked out, so weights are NaN, but later they become numbers.

**Comment by zcq23** [comment]
> Are you sure they are all NaN, and not just the first few? Usually the beginning of chromosomes are repetitive and masked out, so weights are NaN, but later they become numbers.

ohhhhhhhhhhhhhhhhhhhh yes yes the number come the later! I was so careless to check the details of the content😂thank a lot and have a goooooooooooooooooooooooood day !!!!!!!!!!!!!!!!!!!!
