### ISSUE TITLE
an error when i run cooler balance

### ISSUE THREAD

**Issue by fengchuiguo1994** [open2c/cooler#442]
When i run cooler balancer, i got an error
`
cooler balance --max-iters 500 aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool 

Traceback (most recent call last):
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/cooler/cli/balance.py", line 162, in balance
    if name in grp['bins'] and not stdout:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/data/home/ruanlab/huangxingyu/miniconda3/envs/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'bins' doesn't exist)"

cooler ls aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/1000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/2000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/2500
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/5000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/10000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/20000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/25000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/50000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/100000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/200000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/250000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/500000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/1000000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/2000000
aligndir/Sample1_cancer.dedup.pairs.gz.pairs.cut.hic.mcool::/resolutions/2500000
`

my environment
`
python 3.8.0

pip list
Package             Version
------------------- ---------
asciitree           0.3.3
asttokens           2.2.1
backcall            0.2.0
bioframe            0.6.1
biopython           1.81
blosc2              2.0.0
certifi             2024.2.2
charset-normalizer  3.3.2
click               8.1.3
contourpy           1.0.7
cooler              0.9.3
cooltools           0.7.1
cycler              0.11.0
Cython              0.29.34
cytoolz             0.12.1
decorator           5.1.1
Deprecated          1.2.13
dill                0.3.6
exceptiongroup      1.1.1
executing           1.2.0
fonttools           4.39.3
future              0.18.3
h5py                3.8.0
hic2cool            0.5.1
HiCExplorer         3.7.3
HiCMatrix           7
hicrep              0.2.6
idna                3.6
imageio             2.33.1
importlib-metadata  7.0.1
importlib-resources 5.12.0
iniconfig           2.0.0
intervaltree        2.1.0
ipython             8.12.2
jedi                0.18.2
Jinja2              3.1.2
joblib              1.3.2
kiwisolver          1.4.4
krbalancing         0.5.0b0
lazy_loader         0.3
llvmlite            0.41.1
MarkupSafe          2.1.2
matplotlib          3.7.1
matplotlib-inline   0.1.6
msgpack             1.0.5
multiprocess        0.70.14
networkx            3.1
numba               0.58.1
numexpr             2.8.4
numpy               1.24.4
packaging           23.1
pandas              1.5.3
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
Pillow              9.5.0
pip                 23.0.1
pluggy              1.0.0
prompt-toolkit      3.0.38
psutil              5.9.5
ptyprocess          0.7.0
pure-eval           0.2.2
py-cpuinfo          9.0.0
pyBigWig            0.3.22
pyfaidx             0.7.2.1
pyGenomeTracks      3.0
Pygments            2.15.1
pypairix            0.3.7
pyparsing           3.0.9
pysam               0.21.0
pytest              7.3.1
python-dateutil     2.8.2
pytz                2023.3
PyWavelets          1.4.1
PyYAML              6.0
requests            2.31.0
scikit-image        0.21.0
scikit-learn        1.3.2
scikit-misc         0.2.0
scipy               1.10.1
seaborn             0.12.2
setuptools          66.0.0
simplejson          3.19.1
six                 1.16.0
sortedcontainers    2.4.0
stack-data          0.6.2
tables              3.8.0
threadpoolctl       3.2.0
tifffile            2023.7.10
tomli               2.0.1
toolz               0.12.0
traitlets           5.9.0
typing_extensions   4.5.0
tzdata              2023.3
Unidecode           1.3.6
urllib3             2.2.0
wcwidth             0.2.6
wheel               0.38.4
wrapt               1.15.0
zipp                3.15.0
`

**Comment by Phlya** [comment]
Looks like you are using an .mcool file with multiple resolutions in it. You need to balance each resolution one by one.
You can check what resolutions u have using `cooler ls`, and then balance using `cooler balance file.mcool::resolutions/10000` - replace 10000 with your resolution. You can also use bash to simple iterate over the output of `cooler ls`. Hope this helps!
