### ISSUE TITLE
how install hicpro correctly

### ISSUE THREAD

**Issue by qm713152** [open2c/cooler#444]
(hicpro) qm@DESKTOP-334CEMV:~/HiC-Pro-3.1.0$ make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/home/qm/HiC-Pro-3.1.0'
./scripts/install/install_dependencies.sh -c ./config-install.txt -p /usr/local/bin/ -o /usr/local/bin//HiC-Pro_3.1.0 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation !
Checking dependencies
- Python libraries ...
Can not proceed without the required Python libraries, please install them and re-run
make[1]: *** [scripts/install/Makefile:41: configure] Error 1
make[1]: Leaving directory '/home/qm/HiC-Pro-3.1.0'
make: *** [Makefile:40: configure] Error 2

**Comment by Phlya** [comment]
We are not the developers of HiC-Pro, please ask your question to them: https://github.com/nservant/HiC-Pro
