### ISSUE TITLE
access HTTP or FTP URI of cool files?

### ISSUE THREAD

**Issue by lidaof** [open2c/cooler#63]
Hi, 

What does the cooler URI mean?
I am trying to run `cooler info` against a HTTP URL of a `.cool` file, but get `OSError` error.
Thanks.
```
$ cooler info -h
Usage: cooler info [OPTIONS] COOL_PATH

  Display file info and metadata.

  COOL_PATH : Path to a COOL file or Cooler URI.

Options:
  -f, --field TEXT  Print the value of a specific info field.
  -m, --metadata    Print the user metadata in JSON format.
  -o, --out TEXT    Output file (defaults to stdout)
  -h, --help        Show this message and exit.
```

**Comment by nvictus** [comment]
Cooler URI refers to the filepath + optional resource path within the file, described [here](http://cooler.readthedocs.io/en/latest/api.html#uri-string). Direct HTTP access is not supported yet.

**Comment by lidaof** [comment]
Thanks for reply @nvictus. Is there any plan to support direct HTTP access in the future?
