### ISSUE TITLE
Check UCSC / ensebl notation

### ISSUE THREAD

**Issue by joachimwolff** [open2c/cooler#96]
If you load `cooler_file.matrix(balance=False, sparse=True).fetch(chrom)` but you do not know if the cooler file you are opening contains UCSC or ensebl annotated chromosomes, it crashes if you pick the wrong format. 
It would be nice to have a feature like a conversion to the other format in case it fails and another try to load it. The implementation as it is returns a ` ValueError: Unknown sequence label: chrX` which is either caused by the wrong format or because the value is really not there.

**Comment by nvictus** [comment]
I agree. Incompatibility of UCSC and Ensembl style names are frustrating to no end. It doesn't help that sometimes the assemblies do differ! (e.g. hg19 uses a different mitochondrial reference than GRCh37).

I like the idea of automatic retry, though. Another thing that would help is reference name replacement, which should be easy to implement.

**Comment by nvictus** [comment]
Reopening. This hasn't been implemented yet, but in-place scaffold renaming will be available soon as an alternative.

**Comment by joachimwolff** [comment]
Is this already implemented?

**Comment by nvictus** [comment]
yes: https://cooler.readthedocs.io/en/latest/api.html#cooler.rename_chroms
